### ISSUE TITLE
Script fails to find wheel files or zip results.

### ISSUE THREAD

**Issue by kbintermx** [aws-samples/amazon-redshift-udfs#15]
When the script is executed on an EC2 install it fails to define "wheelFile" and execute the find operation.

wheelFile=`find . -name *.whl`

enclosing the wildcard in quotes resolves the issue in this environment:

wheelFile=`find . -name "*.whl"`

Additionally, the script does not zip the files before transporting them with an S3 copy command.

I am proposing a pull request to resolve these.

**Comment by rjvgupta** [comment]
see updated to the depoyFunction.sh and libraryInstaller.sh scripts to satisfy your request.
