### ISSUE TITLE
Questions from AWS customer

### ISSUE THREAD

**Issue by Varshasavya** [aws-samples/amazon-redshift-udfs#18]
Hello Zach,
 
I have a customer that tried to use your script to install a Pip module and has some questions around the github script [https://github.com/aws-samples/amazon-redshift-udfs/blob/master/bin/PipLibraryInstaller/installPipModuleAsRedshiftLibrary.sh] developed by you.
 
Customer questions: 

Q] I _do_ have a lingering question, however, around why the installPipModuleAsRedshiftLibrary.sh script didn't work? In the future, it might be nice to use this, but it didn't seem like Redshift liked me uploading the wheel files it generated... Can you let me know if the Redshift engineers have a fix or workaround for this? Or let me know if I've used the script incorrectly?
 
Let me know.

thanks,
Varsha

**Comment by IanMeyers** [comment]
Can we get the error that was thrown why trying to install the wheel file?

**Comment by Varshasavya** [comment]
Here are the steps followed and the errors encountered by the customer.
-----------

I've been having some trouble trying to load a particular Python package (https://github.com/selwin/python-user-agents) into Redshift as a library. 

Things I've tried:
(1) From the link in the Github repo, I zipped the python-user-agents/user_agents folder, uploaded it to s3 and created the library using a CREATE LIBRARY statement. Once I did this, I wrote a small UDF just importing the relevant class from the user_agents module I wanted to use. However, I got an import error for _a different module_ (ua_parser), which user_agents depends on.
(2) Given the outcome of (1), I figured I needed to have _all_ module dependencies present in the zip file (is this information documented somewhere?). I ended up finding this nifty looking import script from you guys here (https://github.com/aws-samples/amazon-redshift-udfs/blob/master/bin/PipLibraryInstaller/installPipModuleAsRedshiftLibrary.sh), which builds wheel files for a python module and all its dependencies, zips them together and uploads the zip file to s3. After making a couple of modifications (namely, those in: https://github.com/aws-samples/amazon-redshift-udfs/pull/16/files), I uploaded the new user_agents.zip file to s3 and recreated the library in Redshift (along with the test UDF). I got another import error, but this time for the user_agents module itself.

I'd like to be able to use the module import script in the future, so could you tell me what I'm doing wrong? I'm attaching both versions of the python package (from (1) and (2), but I'm attaching them with different names, to be less confusing for you). The CREATE LIBRARY statement I used was:
"""
CREATE OR REPLACE LIBRARY user_agents 
LANGUAGE plpythonu 
FROM 's3://<s3_dir>/user_agents.zip' 
CREDENTIALS '<redshift_iam_role_creds>'
;
"""
(NOTE: again, the zip files _actually_ had the name user_agents.zip at the time of uploading).

The test UDF I wrote was:
"""
CREATE OR REPLACE FUNCTION f_user_agent_test (ua_string VARCHAR)
RETURNS VARCHAR
IMMUTABLE
AS $$
  from user_agents import parse
  return ua_string
$$ LANGUAGE plpythonu
;
"""

And the query I used to validate was:
"""
SELECT f_user_agent_test('blah');

-----------

The error messages were as follows (numbered as in "Things I've tried"):

(1) -----
message: "ImportError: No module named ua_parser"
traceback:  """
line 2, in f_user_agent_test 
File "__init__.py", line 3, in <module> 
File "parsers.py", line 3, in <module>
"""         
-------

(2) ----- 
message: "ImportError: No module named user_agents"
traceback:  "line 2, in f_user_agent_test"
------

**Comment by mfutch78** [comment]
Did you ever resolve this? I'm having the same issue.

**Comment by rjvgupta** [comment]
See latest libraryInstaller.sh this is resolved.

**Comment by Varshasavya** [comment]
Fix included here https://github.com/aws-samples/amazon-redshift-udfs/blob/master/bin/libraryInstaller.sh
