### ISSUE TITLE
[Feature Request] String comparison Python UDF example

### ISSUE THREAD

**Issue by loretoparisi** [aws-samples/amazon-redshift-udfs#40]
Please add an example of advanced string comparison and matching for the UDF Python function. More details [here](https://stackoverflow.com/questions/72462936/function-for-string-column-values-comparison-in-redshift).

**Comment by rjvgupta** [comment]
This has been created.  See the function: [f_fuzzy_string_match](https://github.com/aws-samples/amazon-redshift-udfs/tree/master/python-udfs/f_fuzzy_string_match(varchar%2Cvarchar))
