### ISSUE TITLE
Request: example multi-file UDF

### ISSUE THREAD

**Issue by LanceNorskog** [aws-samples/amazon-redshift-udfs#7]
This and other sample sets have been really nice for understanding a one-file UDF. However, some projects are more complex. Please add a simple example of a multi-file UDF. 

This request is inspired by a situation where it would be great to use the UAP User-Agent Parser project inside a Redshift UDF. This UDF would require code, a configuration file, and the UAP Python library.  Walking through all of the options to make this work is confusing, as I'm not a Python run-time ninja.

**Comment by ajlai** [comment]
I had the same use case (needed ua-parser in a redshift UDF) and put together a library and example here https://github.com/ajlai/uap-redshift.

**Comment by LanceNorskog** [comment]
Thanks!

**Comment by rjvgupta** [comment]
Added the ability to set a requirements.txt file for a list of dependent libraries.  See https://github.com/aws-samples/amazon-redshift-udfs/tree/master/python-udfs/f_ua_parser_family(varchar) for an example.
