### ISSUE TITLE
ua-parser not working: No module named _regexes. Please look at svl_udf_log for more information

### ISSUE THREAD

**Issue by SrdjanNikitovic** [aws-samples/amazon-redshift-udfs#8]
I have created ua-parser.zip, following instructions that have been provided here.

When I extract to check, I see that it has "regexes.py" as well as "user_agent_parser.py"

After creating library in redshift, and trying to do simple user agent parsing, it fails with the following error:
"ImportError: No module named _regexes. Please look at svl_udf_log for more information".

The same code from the function I have tested in terminal using Python and it works.

So there must be some problem how Redshift handles this,

**Comment by rjvgupta** [comment]
See https://github.com/aws-samples/amazon-redshift-udfs/tree/master/python-udfs/f_ua_parser_family(varchar) for an example of how to incorporate the ua_parser.
